service: bundle

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

custom:
  dotenv:
    logging: false
    include:
      - S3_BUCKET
      - S3_REGION
  s3Bucket: ${env:S3_BUCKET}
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.8
  region: ${env:S3_REGION}

functions:
  bundle:
    handler: handler.bundle
    environment:
      S3_REGION: ${self:provider.region}
      S3_BUCKET: ${self:custom.s3Bucket}
