service: bundle

custom:
  dotenv:
    logging: false
    include:
      - S3_BUCKET
      - REGION
  pythonRequirements:
    dockerizePip: true
  s3Bucket: ${env:S3_BUCKET}

plugins:
  - serverless-dotenv-plugin
  - serverless-python-requirements

package:
  exclude:
    - ./event.*
    - package.json
    - yarn.lock
    - ./requirements.txt
    - ./**.sh
    - env/**
    - __pycache__/**
    - node_modules/**
    - .env.exapmle
    - .vscode/**

provider:
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.s3Bucket}/*"
  name: aws
  region: ${env:REGION}
  runtime: python3.8

functions:
  bundle:
    handler: handler.bundle
    environment:
      REGION: ${self:provider.region}
      S3_BUCKET: ${self:custom.s3Bucket}
