service:
  name: freeS3
  # app and org for use with dashboard.serverless.com
  # app: your-app-name
  # org: your-org-name

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  excludeDevDependencies: false

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  # function parameters
  runtime: nodejs12.x
  timeout: 10
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  freeS3:
      handler: handler.freeS3
      events:
        - s3:
          bucket: ${self:provider.s3Bucket}
          event: s3:ObjectRemoved:*
          rules:
            - suffix: .png
          existing: true
      environment:
        S3_REGION: ${env:S3_REGION}
        S3_BUCKET: ${env:S3_BUCKET}
    
    