service:
  name: render

custom:
  dotenv:
    logging: true
    include:
      - REGION
      - S3_BUCKET
  s3Bucket: ${env:S3_BUCKET}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

package:
  excludeDevDependencies: false

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack

provider:
  name: aws
  region: ${env:REGION}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:custom.s3Bucket}/*"
  layers:
    # Google Chrome for AWS Lambda as a layer
    # Make sure you use the latest version depending on the region
    # https://github.com/shelfio/chrome-aws-lambda-layer
    - arn:aws:lambda:${self:provider.region}:764866452798:layer:chrome-aws-lambda:8
  # function parameters
  runtime: nodejs12.x
  memorySize: 2048 # recommended
  timeout: 30
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  render:
    handler: handler.render
    environment:
      REGION: ${self:provider.region}
      S3_BUCKET: ${self:custom.s3Bucket}
